language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
before_script: 
script:
- npm run review
after_success:
  - yarn deploy-storybook --ci --host-token-env-variable=GITHUB_TOKEN
env:
  global:
  - secure: pRfsrahapYSUhXlrYmYTQIKJ1NNPpPsN79Ni/eNbjnUzx4M96zRgyfBkVBg9CEDDXosBbND3E6n+n16EEiyKqWX/PxAU114qD5UEBgUPjSK63asM9Xdj8BD0/lS0z+Bk0qQcLRmLrbODC8ah1TFQFIFSO8uPnSBJOtANaj12xLZRdUUxOzRwh3BRhUMf/b00Lx8xzHJvDnzu0uYIPhvXTme3UKO4RY9DYeIlCxE9cG4dLZQamAE5XbvoLfVxYMf+oVw1dDlV3JuEfqL3B8NP57VsIl37hHlXHkCb3CuZZhFj+VLVCjUbHL9eRhAa3A3Xg1eNUgvvNWdGnNXyQeMdx1StMHYPjaN1OGtIaWmIFS8er/WSKAIcNiCJDGyUpZhRKi9ihGnTnDE2lhGJmbF+il+//h22dNQysRoJvIwz+vYelsQb41+IqWbAPsLgpNLNrXbVuo1idnUVnoZQ1FYT4fZGLRd2HZcuu4Uu4tSy34OYWzioIJgCivFtmlLaJGOKL7URIdW+eCd7pKus0nV29rW+NrfGAALUptFwMqaUEeFQZp5gcnREvaD0pBDElLgw+vGvJIFAF6a+UbHibHR/Kh9Oud9kfOiYuJhDFKvAFLGt7xRfGMqvCDiW+nHr8okOKVrueF9so9qG7l5ENQiT5/d7NefjWV/tTiCEmS2Dtf4=
branches:
  only:
  - master
deploy:
  matrix:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    on:
      branch: gh-pages
  - provider: npm
    email: david@ouanounou.fr
    api_key:
      secure: LLevJagJOErl3MsEjnsSV7cVThTatl/i9jZIcLb9DFNpwl1t/QAzQayMrR0/rdO+Tf5cm3OpNlkNl7MP087DF4J/2bpe5+f3knHjFij5azlKasU+Vp+qjRZ8iWW7tFGbADM61zL8s0I1lyxqzK0o4Bkd+1H6uyKwstLAG1dX6L8InlVoKjBVVpmfjFqNhIbW0dSg5kj3hTTagSF0KV/uR3qWRQSVdcefWNvxviFwnEuDIdRJyHKfMm8v0lZuNDjh96TccCzOPRUNXh9mFHn5vvowEMyz36m7RKwxq6jsg8TcE996WIrA5M4guZehtELz7/MfKUGGqcKBwwiG/z7ccOKmn33k+Qk0Ry68Hgpoqj9nvVVxLjvk9JdKznRXs9Ito2IJ6C92u39klAEg9ovMBF2zijsSj+7HSa4eztDg6jKOh71XZYrMl1T1AqLPYWmvH+V2lIBrsvp/WGAgIsXpz3PtytIDztW0Kx4ESZZGCOUyHrMxZLSC0bysfJoBda0bmqsXB+KRnAR3Xnc3SASarWA2CgGFxgRsFp7NDrmZbXRJKTj5OYZeezXqud9kvSZYeJ8qoSSNFiKIuOhBnnh480nnP8t9jX7n6uBc7lKIADoIAn4YZ0UZCbVxoFZXajeAxQN/WrRIrTKpCZP5jaUZacOxxp06g0ArJCN79wPAqrg=
